name: 'PR-Pilot Code Review'
description: 'AI code review with 4D analysis: semantic, architectural, historical, clone. 16 langs + text fallback.'
author: 'PR-Pilot'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}
  llm_api_key:
    description: 'API key for the LLM (OpenAI-compatible)'
    required: true
  llm_base_url:
    description: 'Base URL for LLM API (OpenAI-compatible)'
    required: false
    default: 'https://api.openai.com/v1'
  llm_model:
    description: 'LLM model name for analysis'
    required: false
    default: 'deepseek-chat'
  embedding_api_key:
    description: 'API key for embedding API (OpenAI-compatible)'
    required: true
  embedding_base_url:
    description: 'Base URL for embedding API (OpenAI-compatible)'
    required: false
    default: 'https://api.openai.com/v1'
  embedding_model:
    description: 'Embedding model name'
    required: false
    default: 'text-embedding-3-small'
  analysis_mode:
    description: 'Analysis architecture: single or two-stage'
    required: false
    default: 'two-stage'
  retrieval_mode:
    description: 'Retrieval strategy: diff, fast, or precise'
    required: false
    default: 'precise'
  top_k:
    description: 'Number of relevant code snippets to retrieve'
    required: false
    default: '5'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    LLM_API_KEY: ${{ inputs.llm_api_key }}
    LLM_BASE_URL: ${{ inputs.llm_base_url }}
    LLM_MODEL: ${{ inputs.llm_model }}
    EMBEDDING_API_KEY: ${{ inputs.embedding_api_key }}
    EMBEDDING_BASE_URL: ${{ inputs.embedding_base_url }}
    EMBEDDING_MODEL: ${{ inputs.embedding_model }}
    INPUT_ANALYSIS_MODE: ${{ inputs.analysis_mode }}
    INPUT_RETRIEVAL_MODE: ${{ inputs.retrieval_mode }}
    INPUT_TOP_K: ${{ inputs.top_k }}

branding:
  icon: 'eye'
  color: 'blue'
